services:
  - type: web
    name: telegram-accounting-bot
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
   envVars:
  - key: BOT_TOKEN
    value: 7908773608:AAFFqLmGkJ9zbsuymQTFzJxy5IyeN1E9M-U
  - key: MONGO_URI
  - key: BASE_URL
    value: https://winpay999.onrender.com/
